FROM centos:7

RUN yum install -y --nogpgcheck epel-release && \
    yum install -y --nogpgcheck https://repo.saltproject.io/py3/redhat/salt-py3-repo-3002-1.el7.noarch.rpm  && \
    yum update -y && \
    yum install -y virt-what salt-minion nano tree vim-full net-tools git && \
    yum clean all && \
    rm -rf /var/cache/yum

RUN sed -i "s|#master: salt|master: salt-master|g" /etc/salt/minion

ENTRYPOINT ["salt-minion", "-l", "debug"]
